- core/src/main/java/com/adobe/aem/guides/wknd/core/components/impl/BylineImpl.java
> fix for sonarQube rule squid:S2384

- core/src/main/java/com/adobe/aem/guides/wknd/core/components/impl/BylineImpl.java
- ui.content/src/main/content/META-INF/vault/filter.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-experience-fragment/initial/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-experience-fragment/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/experience-fragment-web-variation-template/initial/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/experience-fragment-web-variation-template/policies/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/experience-fragment-web-variation-template/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/landing-page-template/policies/.content.xml
- ui.content/src/main/content/jcr_root/content/experience-fragments/wknd/.content.xml
- ui.content/src/main/content/jcr_root/content/experience-fragments/wknd/en/.content.xml
- ui.content/src/main/content/jcr_root/content/experience-fragments/wknd/fr/.content.xml
- creates sample content structure for experience fragments
- ensures templates for Experience Fragments wknd can be found
- ensures cq:xfVariantType=web is added to templates
> Experience fragment/revisions

- ui.frontend/package.json
- ui.frontend/src/static/article.html
- ui.frontend/webpack.common.js
- ui.frontend/webpack.dev.js
adds a webpack dev server to code against with the ui.frontend module
> Feature - Static web server

- pom.xml
- ui.apps/src/main/content/jcr_root/apps/wknd/components/content/embed/.content.xml
- updates Core components version -> 2.7.0
- adds Embed component proxy
> Core Components 2.7.0

- ui.apps/src/main/content/jcr_root/apps/wknd/components/content/sign-in-buttons/current-user.html
- ui.apps/src/main/content/jcr_root/apps/wknd/components/content/sign-in-buttons/sign-in-buttons.html
- ui.frontend/src/components/content/sign-in-buttons/sign-in-buttons.js
It is better to use the OOTB currentuser.json end-point (which exposes XSS protected username/userid for display later).
> Fix/sign up buttons to use OOTB currentuser JSON endpoint

- ui.content/src/main/content/jcr_root/content/wknd/.content.xml
- ui.frontend/src/components/content/tabs/_tabs.scss
- ui.frontend/src/components/content/tabs/styles/_default.scss
- ui.frontend/src/site/main.scss
- ui.frontend/stories/tabs.stories.js
- default styles for the Tab component
> Tab Component

- ui.frontend/src/components/content/carousel/_carousel.scss
- ui.frontend/src/components/content/carousel/styles/_default.scss
- ui.frontend/src/components/content/carousel/styles/_hero.scss
- ui.frontend/src/components/content/carousel/styles/_mini.scss
- ui.frontend/stories/carousel.stories.js
Updates to carousel styles to include a mini height version with a max height of 400px:
> Feature Carousel Styles

- ui.frontend/src/components/content/button/styles/_default.scss
- ui.frontend/src/components/content/carousel/styles/_hero.scss
- ui.frontend/src/components/content/layout-container/styles/_fixed-width.scss
- ui.frontend/src/components/content/teaser/_teaser.scss
- ui.frontend/src/components/content/teaser/styles/_default.scss
- ui.frontend/src/components/content/teaser/styles/_featured.scss
- ui.frontend/src/components/content/teaser/styles/_hero.scss
- ui.frontend/src/components/content/teaser/styles/_list.scss
- ui.frontend/stories/teaser.stories.js
- hero teaser
- featured teaser
- list-style teaser
> teaser style updates for landing page

- ui.frontend/src/main/webpack/site/util.js
> added touchstart and touchmove eventhandlers

- ui.content.sample/src/main/content/jcr_root/content/wknd/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/content-page/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-page/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/adventure-page-template/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/article-page-template/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/content-page-template/structure/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/landing-page-template/structure/.content.xml
- ui.content/src/main/content/jcr_root/content/wknd/.content.xml
> Update cq:deviceGroups path to remove hard coded /etc

- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/en/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/en/featured/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/en/featured/camping-western-australia/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/en/featured/camping-western-australia/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/en/featured/guide-la-skateparks/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/ca/en/featured/guide-la-skateparks/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/featured/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/featured/camping-western-australia/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/featured/camping-western-australia/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/featured/guide-la-skateparks/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/featured/guide-la-skateparks/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/featured/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/featured/camping-western-australia/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/featured/camping-western-australia/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/featured/guide-la-skateparks/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/featured/guide-la-skateparks/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/wknd/ca/en/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/wknd/us/en/.content.xml
- ui.content/src/main/content/jcr_root/content/experience-fragments/wknd/.content.xml
> Issue 135/experience fragment datalayer

- pom.xml
> added cloud manager toolchain plugin to compile with JDK11

- ui.frontend/src/main/webpack/components/contentfragment/js/contributor.js
- ui.frontend/src/main/webpack/components/contentfragment/scss/contentfragment.scss
- ui.frontend/src/main/webpack/components/contentfragment/scss/styles/_contributor.scss
- ui.frontend/src/main/webpack/components/contentfragment/scss/styles/_default.scss
- ui.frontend/src/main/webpack/site/main.js
Implements #156
Note that the WKND CF Policy has NOT been updated in this PR at this time, to allow for folks to experience creating this Style rule themselves in AEM Policy Editor
> #156 - Contributor content fragment styles

- pom.xml
Updated Core Components dependency to 2.12.1
Update for issue #159 
Updates the Core Component dependency that will be embedded and deployed when using the `classic` profile. AEM as a Cloud service deployments already use this.
> updated to core components to 2.12.1

- it.tests/pom.xml
Bumps junit dependency
Based on recommendations from: https://github.com/advisories/GHSA-269g-pwp5-87pp
> bump Junit dependencies

- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/adventures/adventures-2021/master/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/adventures/bali-surf-camp/card/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/adventures/bali-surf-camp/hero-banner/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/us/en/adventures/bali-surf-camp/master/.content.xml
Related to PR #160 
Updated content for issue #160
> updated image filereference

- .gitignore
- ui.frontend/src/main/webpack/components/contentfragment/js/contributor.js
Changed the Contributor Style System JS (DOM adjustment) to use MutationObserver per #175
> #175 - Switch from DomNodeInserted event handler to MutationObserver

- pom.xml
Upgrades Core Component dependency to 2.13.0.
Tracked by issue #182
> upgrade to 2.13.0

- core/pom.xml
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/ImageList.java
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/BylineImpl.java
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImpl.java
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/package-info.java
- core/src/test/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImplTest.java
- ui.apps/src/main/content/jcr_root/apps/wknd/components/image-list/image-list.html
- ui.apps/src/main/content/jcr_root/apps/wknd/components/image-list/item.html
Adds Adobe Client Data Layer capabilities to the Image List component
Tracked by issue #128 
Provides an example of implementing the Data Layer for a custom component.
> initial implementation data layer for Image List component

- ui.tests/test-module/specs/aem/sites.js
The default sites test targets a page that cannot be updated because the title is inherited from the blueprint. This PR updates the test to target the language-master page which should be modifiable.
Running UI tests will fail on this project.
> Update UI test to target a page that can be updated

- pom.xml
Updated version of included Core Components to 2.14.0
Tracked by issue #196 
WKND Reference Site should use the latest Core Components.
> updated core component version to 2.14.0

- analyse/pom.xml
- pom.xml
Adds Analyser Module
Fix for Issue #199 
Aligns project to Archetype 25.
> Issue 199/analyser module

- README.md
Issue #206 
Improves documentation for beginners.
Please see issue.
> Include maven build information specific to IDE

- pom.xml
fixes #204 : Update to Core Components 2.15.0
> Update to Core Components 2.15.2

- ui.content/src/main/content/jcr_root/conf/wknd/settings/graphql/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/graphql/persistentQueries/adventures-all/_jcr_content/_jcr_data.binary
Add persistent query for WKND adventures initial filter
To be used in https://github.com/adobe/aem-guides-wknd-graphql
not tested
> GRAPHQL Add persistent query

- .github/workflows/maven.yml
- README.md
> updated ci build, added badge

- dispatcher/src/conf.dispatcher.d/filters/filters.any
Updated dispatcher config to allow persisted query endpoints to work
Needed for PR #217 to work correctly on Publish + Dispatcher environment.
> updated filter to allow for persisted query

- pom.xml
> update scm connection

- analyse/pom.xml
skip deployment during release since no artifacts generated
> skip deploy

- analyse/assembly.xml
- analyse/pom.xml
include a generated artifact by the analyse module to avoid a deployment failure.
> include a generated artifact for analyse module

- ui.content.sample/src/main/content/jcr_root/content/wknd/.content.xml
- ui.content/src/main/content/jcr_root/content/wknd/.content.xml
see https://github.com/adobe/aem-guides-wknd/issues/235
Local AEM SDK setup and deploy code of my fork
> Switch root page to use Core Component Page to do the redirect

- .github/workflows/deploy-to-wknd-prod.yml
- README.md
See #239
Avoid manual merges from Github repository to AEM Cloud Manager repository.
* Initially configured the `issue/239` branch in my fork to update a branch in the AEM Cloud Manager repository.
* Requires setting few secrets: target Cloud Manager repository and dev/prod branch names, as well as user email/name/password to access Cloud Manager repository.
> #239 - Automatically push to WKND.site

- dispatcher/src/conf.dispatcher.d/filters/filters.any
Adding a rule allowing download manifest file
#251
PWA Support
Tested on WKND dev environment
> #251 - Dispatcher rule for Web Manifest

- README.md
> clean up read me

- RELEASING.md
updated release notes to include instructions to use Java 8
> update release notes

- dispatcher/src/conf.dispatcher.d/filters/default_filters.any
> Allow video formats to be downloadable, in the filters

- dispatcher/pom.xml
> Updating the checksum for default_filters.any for allowing video formats to be downloadable

- ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-base/.content.xml
- ui.apps/src/main/content/jcr_root/apps/wknd/components/image/.content.xml
requires Core Components 2.17.10 or newer
> #294 switch to image V3

- ui.apps/src/main/content/jcr_root/apps/wknd/components/page/customfooterlibs.html
- ui.apps/src/main/content/jcr_root/apps/wknd/components/page/customheaderlibs.html
- ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml
- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml
solves issues #307
#307
clean up code to follow adobe best practices
> move clientlib from custom footer include to policy file

- pom.xml
Use latest AEM Analyser plugin
Fix for issue #311
> updated aem analyser plugin

- it.tests/pom.xml
- it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java
Add a simple integration test for the the GraphQL client
Once https://github.com/adobe/aem-headless-client-java has its first release, the SNAPSHOT version can be removed and this PR merged
> GraphQL integration test

- pom.xml
Updates to Core Components 2.18.6
Fix for issue #328
> update core component version

- dispatcher/pom.xml
- dispatcher/src/conf.d/dispatcher_vhost.conf
Relates to https://github.com/adobe/aem-guides-wknd/pull/341
> SITES-5185 - Ensure all GraphQL Queries to publisher are using Persistent Queries and not POST requests also for stage environments

- it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java
Updates integration tests to reflect new CF Models
Fix for issue #349
> Issue 349/graphql it test update

- .github/workflows/maven-release.yml
- .github/workflows/settings.xml
- pom.xml
GitHub workflow to automate the release
> initial commit of workflow to automate release

- pom.xml
- update release plugin for automated releases.
> updated maven release plugin

- ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author/com.adobe.granite.cors.impl.CORSPolicyImpl~wknd-graphql.cfg.json
- ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.publish/com.adobe.granite.cors.impl.CORSPolicyImpl~wknd-graphql.cfg.json
- ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.publish/com.adobe.granite.csrf.impl.CSRFFilter.cfg.json
Updated CORS configs to use wknd-shared, added path for persistent queries on author
> remove global endpoint, add persistent query path

- ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author/com.adobe.granite.csrf.impl.CSRFFilter.cfg.json
- remove global endpoint
- add wknd-shared endpoint
> fix csrf filter config

- pom.xml
update wknd-shared dependency to latest release 2.0.0
> updated wknd shared to 2.0.0

- ui.apps/src/main/content/jcr_root/apps/wknd/components/xfpage/customheaderlibs.html
This PR needs greater than or equal to AEM Cloud Service Release:2022.7.8120
Recently we've added support for personalization in Experience Fragments. In order to leverage that in wknd, enabling personalization by rendering contexthub in experience fragments page component
https://github.com/adobe/aem-guides-wknd/pull/338
> Enable personalization on experience fragments page component

- pom.xml
Upgrading WKND Shared version to 2.1.0
> Ugraded wknd-shared.version to 2.1.0

- ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml
Enable Web optimized delivery for Image Core Component by default (when deployed to AEM CS).
Promote use of Web optimized images when using Core Components!
Deployed to AEM CS Sandbox. 
This flag will be ignored on AEM 6.x and the AEM SDK as they do not support web optimized images.
> Enabled Web optimized image delivery for Image component

- dispatcher/src/conf.dispatcher.d/available_farms/wknd.farm
The marketing parameters include has to be deactivated until the latest version of CM is released.
> Disable marketing parameters file

- .gitignore
- pom.xml
- ui.frontend/README.md
- ui.frontend/package-lock.json
- ui.tests/Dockerfile
- ui.tests/pom.xml
- ui.tests/test-module/README.md
- ui.tests/test-module/package-lock.json
* Updated Node/NPM to 16 for `ui.frontend`
* Switched to `npm ci`
* Added package-lock.json for `ui.tests` (using Node 14 as the ui.tests container is configured to use 14)
* Updated .gitignore to ignore `node` and `node_modules` folders
Fixes #380
> Update Node/NPM versions and switch to reproducible builds

- RELEASING.md
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/package-info.java
- pom.xml
- Updated WKND-Shared version to 2.1.2, to address Content Fragment model's image ref rootpath issue + fix
- Releasing via GitHub Action steps
https://github.com/adobe/aem-guides-wknd/issues/367
- WKND Content Fragment Authoring with images will not have issues to pick images
- Local verification by creating and updating content fragments
- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
> Next release

- pom.xml
Updated WKND Shared version to 2.2.2 to prep the next release
> bumping WKND-Shared version

- core/src/main/java/com/adobe/aem/guides/wknd/core/models/Byline.java
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/BylineImpl.java
- [X ] Bug fix (non-breaking change which fixes an issue)
- [] My change requires a change to the documentation.
> Per 406 modified tests to fix logic

- README.md
- all/pom.xml
- pom.xml
> WKND v3.0.0

- core/src/main/java/com/adobe/aem/guides/wknd/core/models/Byline.java
- core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/BylineImpl.java
> Revert 408 bugfix/issue 406

- pom.xml
Updated the included WKND Shared version to v3.1.0 (from v3.0.0) to include the new Content Fragment AEM tags.
> Upgrade WKND Shared inclusion to v3.1.0

- README.md
- pom.xml
* updated Core WCM Components dependency to 2.23.2
* updated uber.jar.version to 6.5.17
* update aem-analyse plugin to 1.5.8
* updated AEM SDK API version to 2023.7.12874.20230726T072051Z-230702
SITES-15239
> SITES-15239 - Update projects after Core WCM Components 2.23.2 release

- pom.xml
* updated core.wcm.components.version to 2.23.4
> SITES-16047 - Updated related projects after Core WCM Components Release 2.23.4

- core/pom.xml
- pom.xml
* updated to Core WCM Components 2.24.0
> SITES-16185 Release Core Components 2.24.0 - Post Release

- ui.tests/test-module/run.sh
The proxy changes have been added with a previous PR though are slightly incomplete
In case the proxy is not available, the UI test would be started and then most likely fail
Thus adding the proxy availability check, same as on https://github.com/adobe/aem-test-samples/pull/93/files
> CQ-4355928: add proxy availability check

- ui.tests/test-module/cypress/support/aem.js
Fixed UI tests. Added rewrite from default vhost to wknd vhost.
https://jira.corp.adobe.com/browse/CQ-4356927
Encountering pipeline issue. UI testing on WKND fails.
Successfully run wknd-sandboxes-full-stack pipeline.
> CQ-4356927 UI Tests in WKND project fails

- pom.xml
* updated to Core WCM Components 2.25.4
> SITES-20680 - Post Release - Core Components 2.25.4

- .github/workflows/maven.yml
- pom.xml
> core components release 2.26.0

- core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImpl.java
- core/src/test/java/com/adobe/aem/guides/wknd/core/models/impl/BylineImplTest.java
The PR removes the usage of the guava library from the java code.
Since the guava library bundle will not be available anymore in AEMaaCS and AEM6.5 LTS at some time the installation of the core bundle will fail without this removal.
> remove guava usage from java code

- pom.xml
https://github.com/adobe/aem-guides-wknd/issues/468
> Update to Core Components 2.27.0

- pom.xml
* updated to Core WCM Components 2.28.0
> SITES-25136 - [CoreCmp] Post Release 2.28.0

- ui.frontend/src/main/webpack/components/languagenavigation/languagenavigation.js
added the active language in the label
Ticket: [SITES-24959](https://jira.corp.adobe.com/browse/SITES-24959)
> SITES-24959 The visible label for the toggle language link is different to the label in code
