pom.xml
ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-base/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/accordion/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/accordion/_cq_editConfig.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/accordion/_cq_template/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/button/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/container/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/download/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/experiencefragment/.content.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/content/experiencefragment/_cq_editConfig.xml

Updates the WKND guide for the recent [Core Components 2.5.0 release](https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.5.0).
- updates core components dependencies 2.4.0 -> 2.6.0
- adds proxy components for accordion, button, container, download, experience fragment
- adds accordion clientlib embed
@godanny86

Core Components 2.6.0

---

ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-base/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/_rep_policy.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/article-page-template/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/experience-fragment-web-variation-template/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/landing-page-template/policies/.content.xml

this avoids duplicate minification in production environments (since the css/js from the ui.frontend module has already been minified)

moving site clientlibrary to be included via template

---

ui.apps/src/main/content/jcr_root/apps/wknd/components/content/image/_cq_editConfig.xml

- accepts expects a regex, escape the +
Issue surfaced in:
https://github.com/adobe/aem-core-wcm-components/issues/825, 
Fixed in:
**AEM Core Components** https://github.com/adobe/aem-core-wcm-components/pull/826
**AEM Project Archetype** https://github.com/adobe/aem-project-archetype/pull/268
This pull request addresses a solution in the WKND tutorial image proxy.

[Image] Drag & drop SVG on image component not working

---

pom.xml

Updates Core Components to [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.8.0).

Updates Core Components to 2.8.0

---

pom.xml

#65 - Increased junit-bom dependency version to 5.5.2 to allow isolated IDE JUnit test runs

Fix/65 - Increased junit-bom dependency version to 5.5.2 to allow isolated IDE JUnit test runs

---

pom.xml

There's a couple of ways to do this, but this felt like the safest to me. With these changes, the Java _release_ will be set to 11 all the time, but the toolchains plugin will only be used when run inside Cloud Manager. The toolchains plugin configuration could also be moved into the normal build section (i.e. outside of a profile), but that's a bit more intrusive.

use Java 11 compiler in Cloud Manager and set release to 11. fixes #122

---

core/pom.xml

Relaxed WKND Core bundle imports to expand compatibility across various 6.4.x and 6.5.x releases.
These changes are bound to the `classic` profile, so should not affect AEM as a Cloud Service deployments whatsoever.
This fixes #148 
The prior build did not allow the WKND bundle to start on AEM 6.5.5
Tested on 6.5.5. 
This fix expands allowed dependency version ranges for the unsatisfied imports on 6.5.5 to allow the versions exported by 6.5.5. All of these adjustments are less than what was derived by 6.4.4 uberjar, but in the same Major version (so upper bounds stay the same).

#148 - Relaxed specific bundle imports to support installation on 6.x 

---

pom.xml

Downgrades the maven-compiler version to JDK 1.8
Fix for Cloud Manager Integrated Tests issue, #153 
Allows Stage +Production pipelines in AEM as a Cloud Service to complete
Tested locally and using AEM as a Cloud Service environments.

downgrades maven compiler-version to 1.8

---

ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/content-page/initial/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/content-page/structure/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-page/initial/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-page/structure/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/adventure-page-template/structure/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/article-page-template/structure/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/content-page-template/structure/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/experience-fragment-web-variation-template/structure/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/landing-page-template/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/content-page/initial/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/content-page/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-page/initial/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/template-types/empty-page/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/adventure-page-template/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/article-page-template/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/content-page-template/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/experience-fragment-web-variation-template/structure/.content.xml
ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/landing-page-template/structure/.content.xml

Removes `layout="responsiveGrid"`  property on editable Layout Containers in Template Structure. This property is added in the Initial Content structure for each template, so it is redundant. It also has the negative effect of showing the Layout Container as blank in AEM 6.x.x. 
Removing this property will not effect the responsive features of the layout container(s) when editing a page created based on one of these templates.
This issue fixes issue #177

removed property on editable layout containers

---

ui.tests/pom.xml

Changes the `tarLongFileMode` in the **UI.Tests** module from `gnu` to `posix`. 
Fixes for issue #195 and #189
Some users are unable to build the ui.tests module.

switched from gnu to posix

---

dispatcher/pom.xml

Skips Dispatcher enforcement plugin for users on windows environments.
Fixes for issue #201 and #179 
Some Windows users experience a Maven enforcer issue where it appears that default dispatcher files have been modified. Unclear if this is a result of differences between Mac and Windows or something that occurs during the checkout process. Most users simply want to install the code base to a local environment and this check is unnecessary. Removing the enforcement for windows builds.

skips enforce for windows users

---

ui.content.sample/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/site/header/master/.content.xml
ui.content/src/main/content/jcr_root/content/experience-fragments/wknd/language-masters/en/site/header/master/.content.xml

Updates the Search path for the Quick Search component as part of the Experience Fragment. 
Fix for issue #215 
The current path did not point to a valid page and thus the component defaulted to searching beneath the current page only. This update points to a valid Language Master page and thus will also be localized appropriately for the language structure.
Tested locally and on AEM as a Cloud Service.
Resolves correctly for multi-lingual sites. For example if you search for "Hiking" within the Canadian / English site only search results within `ca/en` will be returned.

fixes incorrect path

---

dispatcher/src/conf.d/available_vhosts/wknd.vhost
dispatcher/src/conf.d/rewrites/rewrite.rules

AEM as a Cloud Services comes with CDN per default. The default headers of AEM, as of April 2021, do not optimize cache-hit-ratio with the CDN, and therefore accelerate the site experience. This patch adds httpd config to add extra headers.
1. Removing the User-Agent from the vary header, that is fragmenting the CDN cache
2. Add headers for resources optimized based on resource type (mutable vs immutable)
3. Add headers to base root redirects to avoid origin requests

#220 Add CDN optimized Cache-Control headers

---

core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImpl.java
core/src/test/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImplTest.java
core/src/test/resources/com/adobe/aem/guides/wknd/core/models/impl/ImageListImplTest.json
ui.frontend/src/main/webpack/components/image-list/scss/styles/_default.scss

Wraps all of the original properties of the referenced image. This includes the timestamp which will make sure that caching/updates to the underlying image behave as expected.
Fixes #218

Avoid 302 redirects for Image List

---

pom.xml
ui.tests/pom.xml

Building this project on a MacOS computer with an Apple M1 chip fails because of the frontend-maven-plugin not supporting it in older versions of that plugin. Therefore updating the frontend-maven-plugin to 1.11.3.
See related change in the frontend-maven-plugin that adds support arm64 binaries:
https://github.com/eirslett/frontend-maven-plugin/pull/970
Now builds on my machine… didn't test on another machine though.
I've also updated the dependency in the `ui.tests` project.

Update frontend-maven-plugin for project to build on Macs with M1 chip

---

core/src/main/java/com/adobe/aem/guides/wknd/core/models/HelloWorldModel.java
ui.apps/src/main/content/META-INF/vault/filter.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/image/_cq_editConfig.xml
ui.apps/src/main/content/jcr_root/apps/wknd/components/text/_cq_editConfig.xml
ui.content.sample/pom.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/.content.xml
ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/.content.xml
ui.content.sample/src/main/content/jcr_root/content/dam/.content.xml
ui.content/pom.xml
ui.content/src/main/content/jcr_root/content/dam/.content.xml

Fixes for several warnings triggered in Cloud Manager:
Package | Line Number | Issue
-- | -- | --
com.adobe.aem.guides:aem-guides-wknd.ui.apps:0.3.1-SNAPSHOT | 0 | Node /apps/wknd/components/image/cq:editConfig/cq:inplaceEditing/config   is an OSGi config or install path which contains non-OSGi-related children   that will not be visible to non-administrative users.
com.adobe.aem.guides:aem-guides-wknd.ui.config:0.3.1-SNAPSHOT | 0 | affected path /apps/wknd/osgiconfig overlaps   [com.adobe.aem.guides:aem-guides-wknd.ui.apps:0.3.1-SNAPSHOT]
com.adobe.aem.guides:aem-guides-wknd.core:src/main/java/com/adobe/aem/guides/wknd/core/models/HelloWorldModel.java | 30 | The class or interface org.apache.sling.settings.SlingSettingsService has   been deprecated and is not recommended to be used on …

Issue 245/cm code quality

---

dispatcher/src/conf.dispatcher.d/filters/filters.any
ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author/com.adobe.granite.cors.impl.CORSPolicyImpl~wknd-graphql.cfg.json
ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author/com.adobe.granite.csrf.impl.CSRFFilter.cfg.json
ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.publish/com.adobe.granite.cors.impl.CORSPolicyImpl~wknd-graphql.cfg.json
ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.publish/com.adobe.granite.csrf.impl.CSRFFilter.cfg.json
ui.content/src/main/content/jcr_root/content/_cq_graphql/wknd/.content.xml

This includes additional configurations to enable the WKND GraphQL endpoint at `/content/cq:graphql/wknd/endpoint.json`
- Updates CORS config
- Updates CRSFFilter config
- Updates dispatcher
- Removes unnecessary property on wknd endpoint
Related to issue #248
If a WKND specific endpoint is needed to enable persistent queries, we should also open the wknd specific endpoint to traffic. This will allow users to compare queries against: 
`/content/graphql/global/endpoint.json` vs. `/content/cq:graphql/wknd/endpoint.json`

Fix Enable WKND GraphQL Endpoint

---

ui.content/src/main/content/jcr_root/conf/wknd/settings/graphql/.content.xml

The `jcr:primaryType` of `/conf/wknd/settings/graphql/persistentQueries` should be `cq:Page` else the endpoint to list persisted queries will return an empty list.

Fix jcr primary type for node persistentQueries.

---

dispatcher/pom.xml
dispatcher/src/conf.dispatcher.d/clientheaders/default_clientheaders.any
dispatcher/src/conf.dispatcher.d/filters/default_filters.any

Archetype 28's immutable files update from Dispatcher SDK 2.0.60
Follow up on #259 #247 #246
Immutable dispatcher configuration files should be in sync with contemporary Dispatcher SDK (currently 2.0.60) and Archetype project.
Make diff between dispatcher subproject's src directories between WKND and Archetype.
_mvn clean install_ in both dispatcher subproject and in the root directory
n/a

Archetype 28's immutable files update from Dispatcher SDK 2.0.60

---

dispatcher/src/conf.dispatcher.d/clientheaders/clientheaders.any

As the dispatcher config filters out CORS headers from the pre-flight requests the CORS validation fails on publish instances when using the WKND example together with the SPA Editor or in headless scenarios.

CORS headers pass through to the publish

---

all/pom.xml
pom.xml

Update WKND to latest AEM Analyser 1.1.4.
The WKND codebase (https://github.com/adobe/aem-guides-wknd/blob/master/pom.xml) still uses the AEM Analyser version 0.9.2. The latest version is 1.1.4.
Outdated Version of AEM Analyser

SKYOPS-17977 - Update WKND to latest AEM Analyser

---

dispatcher/src/conf.d/available_vhosts/wknd.vhost
dispatcher/src/conf.d/variables/global.vars

1. Disable the default caching via mod_expires - and reset age to 0 in vhost
2. Avoid cache-control headers being set on 4xx and 5xx
3. Adjust max-age/s-maxage based on longer term testing
These settings are already in production on wknd.site for a while

Improve CDN cache-control settings

---

ui.apps/src/main/content/jcr_root/apps/wknd/components/page/customheaderlibs.html

Remove the custom tag - as Core Components now have their own tag added. @godanny86 might have impact on the tutorial - as in part that has to be removed.

#289 Remove custom canonical URL

---

dispatcher/src/conf.d/available_vhosts/wknd.vhost

First change - make LocationMatch less broad - and only focus on /content. The URL rewriter uses PT (Pass Thru) - with that the LocationMatch is done on the full JCR path.

#288 add /content to match

---

dispatcher/src/conf.d/available_vhosts/wknd.vhost
dispatcher/src/conf.d/rewrites/rewrite.rules

1. change caching strategy to avoid age over-run that makes the browser repeatedly doing a last-modified-since
2. add rules to cache search results
3. add more mime-types in dam
These settings are in production on https://wknd.site/ and https://aemcomponents.dev/

#318 Change CDN cache strategy

---

ui.content.sample/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml

- add async loading to the WKND page policies
Fixes #333 
Note: although Core Components 2.19 is not yet released, this PR can still be merged and won't interfere with the current setup as the new property `clientlibsAsync` will be ignored until 2.19 is used.

Make sure custom clientlibs are loaded asynchronously

---

pom.xml

Update to Core Components 2.19.0.
Warning: the build is failing because the AEMaaCS image used to build the project does not export the 2.19 Core Component packages. This PR should only be merged once the AEMaaCS image contains CC 2.19.

Update to Core Components 2.19.0

---

dispatcher/pom.xml
dispatcher/src/conf.d/dispatcher_vhost.conf
dispatcher/src/conf.dispatcher.d/filters/default_filters.any

Disable POST requests for Graphql persisted queries
Immutable files should not be different between SDK and archetype.

SITES-5185 - Ensure all GraphQL Queries to publisher are using Persistent Queries and not POST requests

---

all/pom.xml
pom.xml
ui.content.sample/pom.xml
ui.content/pom.xml
ui.content/src/main/content/META-INF/vault/filter.xml

- use the `aem-guides-wknd-shared.ui.content` module instead of all
- Ensures that proper dependency chain is used (i.e tags from wknd-shared are install **before** wknd content)

Feature/use uicontent wknd shared 2.0.0

---

it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java

Reverts the use of `org.junit.Assert.assertThrows`
to fix `java.lang.NoSuchMethodError: org.junit.Assert.assertThrows` in CM pipeline
Issue #360

revert junit throws

---

dispatcher/pom.xml
dispatcher/src/conf.d/dispatcher_vhost.conf
dispatcher/src/conf.d/rewrites/default_rewrite.rules
dispatcher/src/conf.dispatcher.d/cache/default_rules.any

GraphQL persisted queries should be cached by default at dispatcher level.
The query parameters sent in the request via dispatcher need to be encoded. One example of such query is
https://publish-p33706-e135212.adobeaemcloud.com/graphql/execute.json/aem-cplotusonlinecommerce-project/getMarketingBannersList%3Btag%3Dmarketing-banner-homepage%3Bpath%3D%2Fcontent%2Fdam%2Faem-cplotusonlinecommerce-project%2Fth%2Fen%2Fhome

SITES-3659 - [Odin] Review Dispatcher config for Odin and contribute generic parts - Persisted queries

---

ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-base/.content.xml

- add core.wcm.components.embed.v1 dependency to site.base clientlib to enable responsive behaviour for the youtube embed.

SITES-10562 - Embed Youtube component not honoring Aspect ratio

---

dispatcher/pom.xml
dispatcher/src/conf.d/available_vhosts/default.vhost
dispatcher/src/conf.d/dispatcher_vhost.conf
dispatcher/src/conf.d/rewrites/default_rewrite.rules
dispatcher/src/conf.dispatcher.d/available_farms/default.farm
dispatcher/src/conf.dispatcher.d/filters/default_filters.any

sync dispatcher immutable files with Dispatcher SDK and image v2.0.166
Since the previous sync of dispatcher immutable files with Dispatcher SDK and image was from version 2.0.120 in August 2022 and AEM CS releases already progressed further, including dispatcher image and SDK tooling containing newer files, it resulted already in customer using latest public AEM CS releases being out of sync and reporting issues like https://github.com/adobe/aem-project-archetype/issues/1043
Hence we propose to sync those files with the ones from the latest Dispatcher SDK and image v2.0.166 in order for validation scripts not to fail in immutable files compatibility check step as described in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/val …

sync dispatcher immutable files with Dispatcher SDK and image v2.0.166

---

ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/policies/.content.xml

Disable lazy loading on Core Components image policy to increase LHS score by reducing CLS.
Disabled lazy loading.
Increase pagespeed/LHS.
In Summit lab.

Disable lazy loading on images to reduce CLS

---

ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-grid/less/grid.less
ui.frontend/src/main/webpack/base/sass/_variables.scss

Update breakpoint to match editor tablet emulator width
Emulator width for tablet in editor is 768px. Since this is the phone breakpoint in the css and variables in wknd, tablet breakpoint gets set to 769px and hence the appropriate styles for tablet are not getting applied in the emulator.
Layout updates can be done in tablet emulator mode in AEM CS page editor.

Update breakpoint to match editor tablet emulator width

---

all/pom.xml
core/pom.xml
pom.xml
ui.content.sample/pom.xml
ui.content/pom.xml

Fixed issue where aem-guides-wknd-shared.ui.content v3.0.0 was being set as a package dependency even in the `-classic` artifact.
This fix sets aem-guides-wknd-shared.ui.content v3.0.0 as a dep in the cloud artifact, and v2.2.2 as a dep in the classic artifact.
Note that the aem-guides-wknd.all-3.0.0-classic.zip in https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-3.0.0 contains this fix retroactively.

Resolved package dependency in classic all project

---

it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java

Remove checking for error message values as these can change over time.
This check will break IT tests for WKND which will block AEM as a Cloud Service releases.
Ran IT tests on AEM as a Cloud Service sandbox.

Removed unnecessary/brittle IT test checks

---

dispatcher/src/conf.d/available_vhosts/wknd.vhost
dispatcher/src/conf.d/variables/global.vars

Simplified CORS configuration by removing ENABLE_CORS variable. The enabling of CORS in Dispatcher is implicit via the addition of the CORS section in the vhost.
Simplify the CORS Dispatcher configuration.
AEM SDK Dispatcher Tools validator, and RDE.

Simplified CORS Dispatcher configuration

---

it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java
ui.content/pom.xml

GraphQL IT tests failing in WKND project due to change in signature of Persisted Queries in WKND Shared 3.x.
Testing on AEM as a Cloud Service Production pipeline deployment.
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.adobe.evergreen.eaas:eaas-test-runner >--------------
[INFO] Building EaaS tests runner 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from shared: file:///shared/m2-repo/com/adobe/aem/cloud/custom-module/0.0.0/custom-module-0.0.0.pom
[INFO] Downloaded from shared: file:///shared/m2-repo/com/adobe/aem/cloud/custom-module/0.0.0/custom-module-0.0.0.pom (379 B at 2.0 kB/s)
[INFO] Downloading from shared: file:///shared/m2-repo/com/adobe/aem/cloud/custom-module/0.0.0/custom-module-0.0.0-jar-with- …
```

Fixed IT Tests to handle updated GQL queries in WKND Shared 3.x

---

dispatcher/pom.xml
dispatcher/src/conf.d/dispatcher_vhost.conf
dispatcher/src/conf.dispatcher.d/filters/default_filters.any

sync dispatcher immutable files with Dispatcher SDK and image v2.0.191
Since the previous sync of dispatcher immutable files with Dispatcher SDK and image was from version 2.0.166 in March 2023 and AEM CS releases already progressed further, including dispatcher image and SDK tooling containing newer files, it resulted already in customer using latest public AEM CS releases being out of sync and reporting issues like https://github.com/adobe/aem-project-archetype/issues/1043
Hence we propose to sync those files with the ones from the latest Dispatcher SDK and image v2.0.191 in order for validation scripts not to fail in immutable files compatibility check step as described in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/vali …

sync dispatcher immutable files with Dispatcher SDK and image v2.0.191

---

ui.frontend/src/main/webpack/site/elements.scss

When using the WKND XFs in Target on a WKND page, the HTML imported into Target contains:
```
<body class="xf-web-container">
 <div class="container">
<div class="root container responsivegrid">
<div id="container-d5e81cbcff" class="cmp-container">
...
```
WKND's css library uses `body .root {` to set spacing at the top of the WKND site with elements.scss:
```
body {
...
.root {
max-width: $max-body-width;
margin: 0 auto;
padding-top:$header-height;
...
```
When a WKND XF is added to a WKND page using the VEC with an imported XF from AEM, the css above is applied to the XF and therefore the component padding-top is set to $header-height.
This can be fixed by fixing the template-type and template for the WKND experience fragment template.
Under ui.content.sample and ui.content the `root` …

Target xf css issue

---

config/README.md
config/cdn.yaml

This PR introduces a configuration folder that includes an example of CDN configuration file. 
It is only meant as a good practise example related to https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/security/cdn-and-waf-rules.html.
**Notes:** This configuration folder is only useful in the context of AEM as a Cloud Service

Add CDN configuration

---

it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java

* Suggest not to check for strict number of results, but checking there's at least one result
Adjust test to be less strict on number of results.
#431 
Better stability of test suite, not dependent on strict number of results

#431 - GraphQlIT tests are too strict

---

it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GetPageIT.java

Revert unintentional change added on #433
in PR #433 there was a faulty IT test that was introduced into the project unintentionally 
This PR fixes the test in GetPageIT
CQ-4354966
Tested running the IT test locally against a AEMCS instance with WKND

Revert wrongly added test in #433

---

ui.tests/.gitignore
ui.tests/test-module/cypress/support/aem.js

fix: allow curly braces in password string
If for a chance the admin password contains curly braces `123{456}` cypress will parse them trying to type the value into the password field.
this behavior has been disabled with this commit 
https://docs.cypress.io/api/commands/type
running locally against an AEMCS instance

fix: allow curly braces in password string

---

dispatcher/src/conf.dispatcher.d/available_farms/wknd.farm

Skyops 69300

---

dispatcher/src/conf.d/available_vhosts/wknd.vhost

The login on the Publish service (asmith/asmith) was not working resulting in 204 responses for **/system/sling/login/j_security_check**. This was happening cause REQUEST_SCHEME value is http (and not https) thus same-origin check fails and forces the CORS processing, thus 204.
https://github.com/adobe/aem-guides-wknd/issues/448
Handle both http and https REQUEST_SCHEME, the SSL termination might happen before request reaches the dispatcher/Apache POD.
Tested on Tech Marketings Sandox and Prod program, see https://wknd.enablementadobe.com/us/en.html

Publish login issue

---

ui.tests/Dockerfile
ui.tests/test-module/cypress/support/aem.js
ui.tests/test-module/run.sh

Fixed UI tests. Added rewrite from default vhost to wknd vhost.
https://jira.corp.adobe.com/browse/CQ-4356927
Encountering pipeline issue. UI testing on WKND fails.
Successfully run wknd-sandboxes-full-stack pipeline.

CQ-4356927 UI Tests in WKND project fails occasionally

---

ui.tests/Dockerfile
ui.tests/test-module/README.md
ui.tests/test-module/cypress/e2e/publicsite.cy.js
ui.tests/test-module/package-lock.json
ui.tests/test-module/package.json

Update cypress ui tests docker container to include cypress version 13.14.1.
CQ-4358343
Builded docker image locally and executed UI tests against WKND sandbox instance using eaas cli - UI tests passed.

Cq 4358343

---

dispatcher/pom.xml
dispatcher/src/conf.d/available_vhosts/default.vhost
dispatcher/src/conf.d/dispatcher_vhost.conf
dispatcher/src/conf.dispatcher.d/available_farms/default.farm
dispatcher/src/conf.dispatcher.d/filters/default_filters.any

sync dispatcher immutable files with Dispatcher SDK and image v2.0.232
Since the previous sync of dispatcher immutable files with Dispatcher SDK and image was from version 2.0.191 in October 2023 and AEM CS releases already progressed further, including dispatcher image and SDK tooling containing newer files, it resulted already in customer using latest public AEM CS releases being out of sync and reporting issues like previously in https://github.com/adobe/aem-project-archetype/issues/1043
Hence we propose to sync those files with the ones from the latest Dispatcher SDK and image v2.0.232 in order for validation scripts not to fail in immutable files compatibility check step as described in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/conte …

sync dispatcher immutable files with Dispatcher SDK and image v2.0.232

---

dispatcher/src/conf.d/rewrites/rewrite.rules

During UI test run we noticed that homepage is being redirected first to http and then to https instead of https directly.
CQ-4357566
Executed deployment pipeline.

fix for redirecting to http homepage first instead of https

---

it.tests/README.md
it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQLIT.java
it.tests/src/main/java/com/adobe/aem/guides/wknd/it/tests/GraphQlIT.java

Customer IT tests run after the product tests are run and suppose to test customer's added functionality.
- testQueryWithSyntaxError
- testQueryWithErrorResponse
Those tests were testing `aemHeadlessClient` itself (ability to throw an AEMHeadlessClientException), which should be part of product tests and not a customer IT tests.
- testListPersistedQueries
Test `GraphQLEndpointIT`requred publish instance up and running and having persisted query published, updated documentation to reflect this.
Test GraphQlIT renamed to GraphQ**L**IT, to as L stands for "Language", which is also a part of "GraphQL" abbreviation.
Improve code quality and provide separation of  concerns.
Locally and on cloud environment

GraphQLIT - Improve code quality and provide separation of  concerns.

---

ui.tests/Dockerfile

this pr fixes error during the build:
```
W: GPG error: https://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 32EE5355A6BC6E42
```

fix(build): update public key for google linux pkg repo

---

ui.frontend/src/main/webpack/components/languagenavigation/languagenavigation.js

Added aria-expanded attribute and toggle it
[SITES-24960](https://jira.corp.adobe.com/browse/SITES-24960)

SITES-24960 Language toggle does not communicate correct expanded / collapsed state
